version: "3.8"

services:
  appointments_ms:
    container_name: medisync_appointments_ms 
    image: appointments_ms_img
    build:
      context: ./medisync_appointments_ms
      target: appointment_ms
    ports:
      - 8081:8081
    networks:
      - appriceit-network
    links:
      - "appointments_db:db"
    restart: unless-stopped

  appointments_db:
    container_name: medisync_appointments_db
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medisyncdb
    ports:
      - 5432:5432
    networks:
      - appriceit-network

  users_ms:
    container_name: medisync_users_ms 
    image: users_ms_img
    build:
      context: ./medisync_users_ms
    ports:
      - 6000:6000
    networks:
      - appriceit-network
    links:
      - "users_db:db"
    restart: unless-stopped


  users_db:
    container_name: medisync_users_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - appriceit-network
  

networks:
  appriceit-network:
