version: "3.8"

services:
  appointments_ms:
    hostname: appointments_ms
    container_name: medisync_appointments_ms 
    image: appointments_ms_img
    build:
      context: ./medisync_appointments_ms
      target: appointment_ms
    ports:
      - 8081:8081
    networks:
      - appriceit-network
    links:
      - "appointments_db:db"
    restart: unless-stopped

  appointments_db:
    container_name: medisync_appointments_db
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medisyncdb
    ports:
      - 5432:5432
    networks:
      - appriceit-network

  notification_ms:
    container_name: medisync_notification_ms 
    hostname: notification_ms
    image: notification_ms_img
    build:
      context: ./medisync_nofications_ms
    ports:
      - 8888:8888
    networks:
      - appriceit-network
    links:
      - "notification_db:db"
    restart: unless-stopped

  notification_db:
    container_name: medisync_notifications_db
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notifydb
    networks:
      - appriceit-network
  users_ms:
    container_name: medisync_users_ms 
    hostname: users_ms
    image: users_ms_img
    build:
      context: ./medisync_users_ms
    ports:
      - 6000:6000
    networks:
      - appriceit-network
    links:
      - "users_db:db"
    restart: unless-stopped


  users_db:
    container_name: medisync_users_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - appriceit-network

  auth_ms:
    container_name: medisync_auth_ms 
    hostname: auth_ms
    image: auth_ms_img
    build:
      context: ./medisync_auth_ms
    ports:
      - 80:80
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/?authSource=admin
    networks:
      - appriceit-network
    links:
      - "auth_db:db"
    restart: unless-stopped

  auth_db:
    container_name: medisync_auth_db
    image: mongo
    restart: always
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - appriceit-network
  

  regmed_db:
    image: mysql:latest
    container_name: medisync_regmed_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: medisync
      MYSQL_PASSWORD: medisync
    restart: unless-stopped
    networks:
      - appriceit-network

  regmed_ms:
    stdin_open: true
    hostname: regmed_ms
    build:
      context: ./MediSync-RegistrosMedicos-MS
    image: img_regmed_ms
    container_name: medisync_regmed_ms
    links:
      - "regmed_db:mysql"
    ports:
      - 5000:5000
    restart: always


  

networks:
  appriceit-network:
